# Generated by Django 4.1.1 on 2022-10-05 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_number', models.PositiveIntegerField(unique=True)),
                ('course_name', models.CharField(max_length=100)),
                ('course_field', models.CharField(default='', max_length=100)),
                ('credit', models.PositiveIntegerField()),
                ('selected_ratio', models.FloatField(default=0.0)),
                ('difficulty', models.FloatField(default=0.0)),
                ('passed_ratio', models.FloatField(default=0.0)),
                ('satisfaction', models.FloatField(default=0.0)),
                ('mocked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.PositiveIntegerField(unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('current_year', models.CharField(max_length=50)),
                ('field_of_study', models.CharField(max_length=50)),
                ('gpa', models.FloatField()),
                ('interested_in_math', models.FloatField(default=0.0)),
                ('interested_in_cs', models.FloatField(default=0.0)),
                ('interested_in_art', models.FloatField(default=0.0)),
                ('interested_in_history', models.FloatField(default=0.0)),
                ('interested_in_literature', models.FloatField(default=0.0)),
                ('interested_in_law', models.FloatField(default=0.0)),
                ('interested_in_philosophy', models.FloatField(default=0.0)),
                ('interested_in_pedagogy', models.FloatField(default=0.0)),
                ('mocked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EnrolledCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mocked', models.BooleanField(default=False)),
                ('course_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.course', to_field='course_number')),
                ('student_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', to_field='student_number')),
            ],
        ),
    ]
