# Generated by Django 4.1 on 2022-08-25 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_number', models.PositiveIntegerField(unique=True)),
                ('course_name', models.CharField(max_length=100)),
                ('credit', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='student_number',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.CreateModel(
            name='EnrolledCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.course', to_field='course_number')),
                ('student_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', to_field='student_number')),
            ],
        ),
    ]
