# Generated by Django 4.1 on 2022-08-25 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_course_alter_student_student_number_enrolledcourse'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EnrolledCourse',
            new_name='EnrolledCourses',
        ),
    ]
