# Generated by Django 4.1 on 2022-09-15 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_rename_enrolledcourse_enrolledcourses'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_field',
            field=models.CharField(default='', max_length=100),
        ),
    ]
