# Generated by Django 4.1.1 on 2022-09-24 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_course_difficulty_course_passed_ratio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AddField(
            model_name='student',
            name='credits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.IntegerField(default=1),
        ),
    ]
