# Generated by Django 4.1.1 on 2022-09-24 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_student_age_student_credits_student_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='mocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='mocked',
            field=models.BooleanField(default=False),
        ),
    ]
