# Generated by Django 4.1.1 on 2022-09-24 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_course_mocked_student_mocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolledcourses',
            name='mocked',
            field=models.BooleanField(default=False),
        ),
    ]
