# Generated by Django 4.1.1 on 2022-09-24 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_enrolledcourses_mocked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='age',
        ),
        migrations.RemoveField(
            model_name='student',
            name='credits',
        ),
        migrations.RemoveField(
            model_name='student',
            name='grade',
        ),
        migrations.AddField(
            model_name='student',
            name='interested_in_art',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='interested_in_cs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='interested_in_history',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='interested_in_law',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='interested_in_literature',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='interested_in_math',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='interested_in_pedagogy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='interested_in_philosophy',
            field=models.BooleanField(default=False),
        ),
    ]
